### ISSUE TITLE
Allow user to select the location of the new parking spots on the map

### ISSUE THREAD

**Issue by sean-prz** [SwEnt-Fall-2024-Group-22/Cyrcle#72]
#### Problem   
The current locationPicker screen doesn't allow the user to choose a location

#### Solution
The user should be able to select the Location of the new Parking Spot in as little click as possible. 
First the user set the top left corner then the right one.

#### Task

- [x] Save the location in the mapViewModel for the next screen 
- [x] Fix the test : now that the db has actual elements some tests fail
- [x] Make UI test
